home:
    path: /
    controller: App\Controller\DefaultController::home

addQuestion:
    path: /addQuestion
    controller: App\Controller\DefaultController::addquestion

profile:
    path: /profile/{user}
    controller: App\Controller\DefaultController::profile

settings:
    path: /settings
    controller: App\Controller\DefaultController::settings

title:
    path: /title/{question}
    controller: App\Controller\DefaultController::title
