nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ["*"]
        allow_headers: ["*"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        max_age: 3600
    paths:
        '^/': ~